name: Update M3U8

on:
  workflow_dispatch:  # Bu hissə sayəsində əl ilə işə salmaq mümkün olur

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Reponu klonla
        uses: actions/checkout@v3

      - name: Python quraşdır
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: M3U8 faylını yarat
        run: python generate_m3u8.py

      - name: Yaranmış faylı commit et
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add trt_haber_live.m3u8
          git commit -m "🔁 Əl ilə yeniləmə" || echo "No changes to commit"
          git push
