jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Create cookies.txt
        run: echo "${{ secrets.COOKIES_TXT }}" > cookies.txt

      - name: Playlist yarat (debug)
        shell: bash
        timeout-minutes: 5
        run: |
          set -x
          python generate_m3u.py
