name: Generate and Commit M3U Playlist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Hər gün UTC ilə 12:00-da işə düşəcək

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # persist-credentials default: true, GITHUB_TOKEN avtomatik konfiqurasiya olunur

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create cookies.txt from secret
        run: |
          echo "${{ secrets.COOKIES_TXT }}" > cookies.txt

      - name: Generate playlist.m3u (debug)
        shell: bash
        timeout-minutes: 5
        run: |
          set -x
          python generate_m3u.py

      - name: Commit and push playlist.m3u if changed
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u
          if ! git diff --cached --quiet; then
            git commit -m "Avtomatik yenilənmiş playlist.m3u"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
          else
            echo "Heç bir dəyişiklik yoxdur → push edilmədi."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
