name: YouTube Auto Downloader

description: >
  YouTube kanalından son videonu avtomatik və ya əl ilə tapıb yükləyir.

version: "1.1"

dependencies:
  - python>=3.8
  - feedparser
  - yt-dlp

settings:
  channel_id: "UCOqe-z52nnpVSAe8Ds0fxaA"
  check_interval_seconds: 300
  last_video_file: "last_video.txt"
  download_folder: "downloads"
  output_template: "%(upload_date)s_%(title)s.%(ext)s"
  mode: "auto"   # "auto" və ya "manual"
